apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
      - name: messaging-app
        image: amosomariba/messaging-app:latest  # Replace with your Docker Hub image
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: "your-mysql-service-name"
        - name: MYSQL_USER
          value: "youruser"
        - name: MYSQL_PASSWORD
          value: "yourpassword"
        - name: MYSQL_DATABASE
          value: "yourdbname"

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
